### ISSUE TITLE
The SPA default page middleware could not return the default page '/index.html'

### ISSUE THREAD

**Issue by shaigalili** [Nordes/HoNoSoFt.DotNet.Web.Spa.ProjectTemplates#47]
InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

fresh install, simply dont run.

**Comment by Nordes** [comment]
Hi Shaigalili, which template were you using? I need more details on what error you're having. I currently build the 2 projects within docker without any issue.

Don't forget that you need to have NodeJs

**Comment by shaigalili** [comment]
Hi Nordes,
I've used this on windows, VS 2019, with NodeJs installed.

**Comment by Nordes** [comment]
Humm I also use that setup. I think you have a specific issue. Have you tried to reload the page after? I know that the wwwroot is empty when the web app starts. You refresh a second after and it's ok.

On my local version, i was tired of F5, so I added the following:

Update `webpack.config.js`
```js
'use strict'
const fs = require('fs') // added
// ....
console.info(`Building for production: ` + isProduction)
rimraf.sync(path.resolve(_rootDir, 'wwwroot/**/*'), { silent: true })

fs.createReadStream(path.resolve(_rootDir, 'build/index.loading.html')) // added
  .pipe(fs.createWriteStream(path.resolve(_rootDir, 'wwwroot/index.html'))) // added
// ...
```

new file created under the build folder `index.loading.html`
```html
<html>
  <head>
    <title>Building...</title>
  </head>
  <body>
    Loading ...
    <script>setInterval(() => {
      location.reload()
    }, 400);</script>
  </body>
</html>
```

**Comment by Nordes** [comment]
Fixed, a loadng "message" is now showing and load the page when ready.

![image](https://user-images.githubusercontent.com/446572/55878168-de2b0100-5bd6-11e9-801a-88aa4caf79cb.png)
